"""AI Daily Insights Database Models - Personalized Astrological Intelligence"""

from sqlalchemy import Column, String, Integer, Float, DateTime, Boolean, Text, JSON, ForeignKey, Enum as SQLEnum
from sqlalchemy.orm import relationship
from datetime import datetime, timedelta
from app.db import Base
import enum
import uuid

# ============================================================================
# ENUMS
# ============================================================================

class InsightType(str, enum.Enum):
    """Types of daily insights"""
    GENERAL = "general"
    LUCKY_TIMES = "lucky_times"
    ROMANCE = "romance"
    CAREER = "career"
    HEALTH = "health"
    FINANCE = "finance"
    LUCKY_NUMBERS = "lucky_numbers"
    TAROT = "tarot"
    NUMEROLOGY = "numerology"


class InsightMood(str, enum.Enum):
    """Emotional tone of insight"""
    POSITIVE = "positive"
    NEUTRAL = "neutral"
    CAUTIOUS = "cautious"
    TRANSFORMATIVE = "transformative"


class InsightStatus(str, enum.Enum):
    """Insight generation status"""
    GENERATED = "generated"
    PERSONALIZED = "personalized"
    SCHEDULED = "scheduled"
    DELIVERED = "delivered"
    FAILED = "failed"


# ============================================================================
# 1. DAILY INSIGHT MODELS
# ============================================================================

class DailyInsight(Base):
    """Daily astrological insights generated by AI"""
    __tablename__ = "daily_insights"
    
    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    
    # Core Content
    date = Column(DateTime, default=datetime.utcnow, index=True)
    zodiac_sign = Column(String(20))  # aries, taurus, etc
    
    title = Column(String(200), nullable=False)
    short_summary = Column(String(500))  # Brief 1-2 line teaser
    full_content = Column(Text)  # Complete insight text
    
    # Metadata
    insight_type = Column(SQLEnum(InsightType), default=InsightType.GENERAL, index=True)
    mood = Column(SQLEnum(InsightMood), default=InsightMood.NEUTRAL)
    confidence_score = Column(Float, default=0.85)  # 0-1, how confident in prediction
    
    # Astrological Data
    moon_phase = Column(String(50))  # new_moon, waxing_crescent, etc
    current_planetary_positions = Column(JSON)  # {planet: sign, ...}
    mercury_retrograde = Column(Boolean, default=False)
    venus_aspects = Column(String(200))  # Specific Venus influence
    mars_aspects = Column(String(200))  # Specific Mars influence
    
    # Content Sections (JSON structured data)
    sections = Column(JSON)  # {
    #   "lucky_times": {"start": "09:00", "end": "12:00"},
    #   "lucky_colors": ["red", "gold"],
    #   "lucky_numbers": [7, 14, 21],
    #   "element_focus": "fire",
    #   "power_affirmation": "I am...",
    #   "tarot_card": "The Magician",
    #   "numerology": {"life_path": 5, "message": "..."}
    # }
    
    # AI Generation Info
    ai_model_version = Column(String(50))  # gpt-4, claude-3, etc
    generation_prompt_hash = Column(String(64))  # Track prompt uniqueness
    generation_method = Column(String(50))  # algorithmic, llm, hybrid
    
    # Performance Tracking
    view_count = Column(Integer, default=0)
    interaction_count = Column(Integer, default=0)  # clicks, shares
    save_count = Column(Integer, default=0)
    
    # Relationships
    user_id = Column(String(36), ForeignKey('user.id', ondelete='CASCADE'), nullable=True)  # If personalized for user
    user = relationship("User", back_populates="daily_insights")
    
    engagements = relationship("InsightEngagementLog", back_populates="insight", cascade="all, delete-orphan")
    feedback_list = relationship("InsightFeedback", back_populates="insight", cascade="all, delete-orphan")
    
    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow, index=True)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    published_at = Column(DateTime, nullable=True)
    
    status = Column(SQLEnum(InsightStatus), default=InsightStatus.GENERATED, index=True)


class DailyInsightPersonalized(Base):
    """Personalized version of daily insight for specific user"""
    __tablename__ = "daily_insights_personalized"
    
    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    
    # Reference to base insight
    base_insight_id = Column(String(36), ForeignKey('daily_insights.id', ondelete='CASCADE'), nullable=False)
    base_insight = relationship("DailyInsight")
    
    user_id = Column(String(36), ForeignKey('user.id', ondelete='CASCADE'), nullable=False, index=True)
    user = relationship("User", back_populates="personalized_insights")
    
    # Personalization Factors
    personalized_title = Column(String(200))
    personalized_content = Column(Text)  # Customized with user's name, history, etc
    
    personalization_factors = Column(JSON)  # {
    #   "used_birth_time": true,
    #   "considered_transit_date": true,
    #   "incorporated_user_preferences": ["career", "romance"],
    #   "personalization_level": 0.9
    # }
    
    # User-Specific Sections
    personalized_sections = Column(JSON)  # Enhanced sections with user data
    user_history_context = Column(String(500))  # Reference to user's past insights
    
    # Delivery Tracking
    scheduled_delivery_time = Column(DateTime, nullable=True, index=True)
    delivered_at = Column(DateTime, nullable=True)
    opened_at = Column(DateTime, nullable=True)
    
    # Engagement
    engagement_count = Column(Integer, default=0)
    time_spent_seconds = Column(Integer, default=0)
    
    # Relationships
    engagements = relationship("InsightEngagementLog", foreign_keys="InsightEngagementLog.personalized_insight_id", 
                              back_populates="personalized_insight", cascade="all, delete-orphan")
    feedback = relationship("InsightFeedback", foreign_keys="InsightFeedback.personalized_insight_id",
                           back_populates="personalized_insight")
    
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)


# ============================================================================
# 2. ENGAGEMENT TRACKING
# ============================================================================

class InsightEngagementLog(Base):
    """Track how users engage with insights"""
    __tablename__ = "insight_engagement_logs"
    
    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    
    # Reference
    insight_id = Column(String(36), ForeignKey('daily_insights.id', ondelete='CASCADE'), nullable=True)
    insight = relationship("DailyInsight", back_populates="engagements")
    
    personalized_insight_id = Column(String(36), ForeignKey('daily_insights_personalized.id', ondelete='CASCADE'), nullable=True)
    personalized_insight = relationship("DailyInsightPersonalized", back_populates="engagements")
    
    user_id = Column(String(36), ForeignKey('user.id', ondelete='CASCADE'), nullable=False, index=True)
    user = relationship("User", back_populates="insight_engagements")
    
    # Engagement Events
    view_count = Column(Integer, default=0)
    opened_at = Column(DateTime, nullable=True)
    time_spent_seconds = Column(Integer, default=0)
    
    # Interactions
    clicked_to_details = Column(Boolean, default=False)
    clicked_lucky_times = Column(Boolean, default=False)
    clicked_lucky_numbers = Column(Boolean, default=False)
    shared_to_whatsapp = Column(Boolean, default=False)
    shared_to_social = Column(Boolean, default=False)
    
    # Save & Favorite
    is_saved = Column(Boolean, default=False)
    saved_at = Column(DateTime, nullable=True)
    
    is_bookmarked = Column(Boolean, default=False)
    bookmarked_at = Column(DateTime, nullable=True)
    
    # Push Notification
    notification_sent = Column(Boolean, default=False)
    notification_opened = Column(Boolean, default=False)
    opened_from_notification = Column(Boolean, default=False)
    
    # Source Tracking
    source = Column(String(50))  # daily_feed, notification, search, share_link
    entry_point = Column(String(50))  # home, settings, notification, etc
    
    created_at = Column(DateTime, default=datetime.utcnow, index=True)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)


# ============================================================================
# 3. USER PREFERENCES & HISTORY
# ============================================================================

class UserInsightPreference(Base):
    """User preferences for daily insights"""
    __tablename__ = "user_insight_preferences"
    
    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    user_id = Column(String(36), ForeignKey('user.id', ondelete='CASCADE'), unique=True, index=True)
    user = relationship("User", back_populates="insight_preferences", uselist=False)
    
    # Delivery Preferences
    insights_enabled = Column(Boolean, default=True)
    delivery_time = Column(String(5))  # HH:MM format, e.g., "08:00"
    timezone = Column(String(50), default="UTC")
    
    # Frequency
    frequency = Column(String(20), default="daily")  # daily, weekly, custom
    
    # Channel Preferences
    send_via_email = Column(Boolean, default=True)
    send_via_push = Column(Boolean, default=True)
    send_via_whatsapp = Column(Boolean, default=False)
    
    # Content Preferences
    preferred_insight_types = Column(JSON)  # ["general", "lucky_times", "career", ...]
    preferred_mood = Column(String(50), default="positive")  # positive, mixed, all
    
    # Personalization Level
    personalization_level = Column(String(20), default="high")  # low, medium, high
    include_birth_chart_insights = Column(Boolean, default=True)
    include_daily_transit_data = Column(Boolean, default=True)
    include_numerology = Column(Boolean, default=False)
    include_tarot = Column(Boolean, default=False)
    
    # Language & Style
    language = Column(String(10), default="en")
    content_length = Column(String(20), default="medium")  # short, medium, long
    writing_style = Column(String(50), default="inspiring")  # inspiring, scientific, mystical
    
    # Zodiac Sign Tracking
    tracked_zodiac_signs = Column(JSON)  # [self, partner, friend, ...]
    
    # Quiet Hours
    quiet_hours_enabled = Column(Boolean, default=True)
    quiet_hours_start = Column(String(5))  # HH:MM, e.g., "22:00"
    quiet_hours_end = Column(String(5))  # HH:MM, e.g., "07:00"
    
    # Engagement Settings
    auto_save_favorites = Column(Boolean, default=False)
    enable_notifications = Column(Boolean, default=True)
    enable_weekly_digest = Column(Boolean, default=True)
    
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)


class InsightHistory(Base):
    """Historical record of all insights viewed by user"""
    __tablename__ = "insight_history"
    
    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    
    user_id = Column(String(36), ForeignKey('user.id', ondelete='CASCADE'), index=True)
    user = relationship("User", back_populates="insight_history")
    
    insight_id = Column(String(36), ForeignKey('daily_insights.id', ondelete='SET NULL'), nullable=True)
    insight = relationship("DailyInsight")
    
    personalized_insight_id = Column(String(36), ForeignKey('daily_insights_personalized.id', ondelete='CASCADE'), nullable=True)
    
    # Content Summary
    title = Column(String(200))
    date = Column(DateTime, index=True)
    zodiac_sign = Column(String(20))
    insight_type = Column(SQLEnum(InsightType))
    
    # Interaction Summary
    viewed = Column(Boolean, default=True)
    viewed_at = Column(DateTime, nullable=True)
    time_spent_seconds = Column(Integer, default=0)
    
    favorites = Column(Boolean, default=False)
    shared = Column(Boolean, default=False)
    rating = Column(Integer, nullable=True)  # 1-5 stars
    
    # Archival
    archived = Column(Boolean, default=False)
    archived_at = Column(DateTime, nullable=True)
    
    created_at = Column(DateTime, default=datetime.utcnow, index=True)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)


# ============================================================================
# 4. FEEDBACK & RATING SYSTEM
# ============================================================================

class InsightFeedback(Base):
    """User feedback on insights for AI training"""
    __tablename__ = "insight_feedback"
    
    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    
    user_id = Column(String(36), ForeignKey('user.id', ondelete='CASCADE'), index=True)
    user = relationship("User", back_populates="insight_feedback")
    
    insight_id = Column(String(36), ForeignKey('daily_insights.id', ondelete='CASCADE'), nullable=True)
    insight = relationship("DailyInsight", back_populates="feedback_list")
    
    personalized_insight_id = Column(String(36), ForeignKey('daily_insights_personalized.id', ondelete='CASCADE'), nullable=True)
    personalized_insight = relationship("DailyInsightPersonalized", back_populates="feedback")
    
    # Rating
    overall_rating = Column(Integer)  # 1-5 stars
    accuracy_rating = Column(Integer, nullable=True)  # How accurate was it (1-5)
    relevance_rating = Column(Integer, nullable=True)  # How relevant (1-5)
    
    # Text Feedback
    comment = Column(Text, nullable=True)
    
    # Structured Feedback
    was_accurate = Column(Boolean, nullable=True)
    was_helpful = Column(Boolean, nullable=True)
    would_recommend = Column(Boolean, nullable=True)
    
    feedback_tags = Column(JSON)  # ["too_generic", "helpful", "accurate", "inaccurate", ...]
    
    # Sentiment Analysis
    sentiment = Column(String(20))  # positive, neutral, negative
    emotion = Column(String(50))  # inspired, skeptical, validated, etc
    
    # For AI Training
    helpful_for_training = Column(Boolean, default=True)
    confidential = Column(Boolean, default=False)
    
    created_at = Column(DateTime, default=datetime.utcnow, index=True)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)


# ============================================================================
# 5. INSIGHT GENERATION LOG
# ============================================================================

class InsightGenerationLog(Base):
    """Log of insight generation processes for monitoring"""
    __tablename__ = "insight_generation_logs"
    
    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    
    # Process Info
    generation_date = Column(DateTime, index=True)
    zodiac_sign = Column(String(20), nullable=True)
    
    # Method
    ai_model_used = Column(String(50))  # gpt-4, claude-3, etc
    generation_method = Column(String(50))  # algorithmic, llm, hybrid
    
    # Performance
    generation_time_seconds = Column(Float)
    cost_estimate = Column(Float, nullable=True)
    tokens_used = Column(Integer, nullable=True)
    
    # Quality Metrics
    confidence_score = Column(Float)  # 0-1
    diversity_score = Column(Float)  # How unique vs previous (0-1)
    personalization_score = Column(Float)  # Quality of personalization (0-1)
    
    # Status
    status = Column(String(50))  # success, partial_success, failed
    error_message = Column(String(500), nullable=True)
    
    # Astrological Data Used
    astrological_factors = Column(JSON)  # moon_phase, retrograde, etc
    
    # Generated Count
    total_generated = Column(Integer, default=0)
    total_personalized = Column(Integer, default=0)
    total_delivered = Column(Integer, default=0)
    total_failed = Column(Integer, default=0)
    
    created_at = Column(DateTime, default=datetime.utcnow)


# ============================================================================
# USER MODEL EXTENSIONS (In actual implementation, add to existing User model)
# ============================================================================

# Add these relationships to the User model:
"""
daily_insights = relationship("DailyInsight", back_populates="user")
personalized_insights = relationship("DailyInsightPersonalized", back_populates="user")
insight_preferences = relationship("UserInsightPreference", back_populates="user", uselist=False)
insight_engagements = relationship("InsightEngagementLog", back_populates="user")
insight_history = relationship("InsightHistory", back_populates="user")
insight_feedback = relationship("InsightFeedback", back_populates="user")
"""
