"""
AstroLuck Intelligence & Analytics Models
Numerology, Probability, and Statistical Analysis
"""

from sqlalchemy import Column, Integer, Float, String, DateTime, ForeignKey, JSON, Boolean, Text
from sqlalchemy.orm import relationship
from datetime import datetime
from .base import Base

class NumerologyProfile(Base):
    """User's complete numerology reading"""
    __tablename__ = "numerology_profiles"
    
    id = Column(Integer, primary_key=True)
    user_id = Column(Integer, ForeignKey('users.id'), unique=True)
    
    # Core numerology numbers (calculated from name + birth date)
    life_path_number = Column(Integer)  # 1-9, 11, 22, 33
    destiny_number = Column(Integer)   # Career and purpose
    soul_urge_number = Column(Integer) # Inner desires and motivations
    personality_number = Column(Integer) # How others perceive you
    expression_number = Column(Integer) # Natural talents and abilities
    birth_day_number = Column(Integer) # Day of birth influence
    
    # Detailed readings (generated by AI)
    life_path_reading = Column(Text)  # Comprehensive interpretation
    destiny_reading = Column(Text)
    soul_urge_reading = Column(Text)
    personality_reading = Column(Text)
    expression_reading = Column(Text)
    birth_day_reading = Column(Text)
    
    # Compatibility scores
    lucky_numbers = Column(JSON)  # Array of lucky numbers [1-9]
    lucky_colors = Column(JSON)   # Array of lucky color names
    lucky_days = Column(JSON)     # Array of lucky day names
    lucky_hours = Column(JSON)    # Array of lucky hours [0-23]
    
    # Compatibility with birth chart
    zodiac_compatibility = Column(JSON)  # Compatibility scores with other signs
    numerology_compatibility = Column(JSON)  # Compatible numerology numbers
    
    # Life predictions
    challenges = Column(JSON)  # Life challenges based on numerology
    strengths = Column(JSON)  # Natural strengths
    karmic_lessons = Column(JSON)  # Lessons to learn
    
    # Personal year number (changes annually)
    personal_year_number = Column(Integer)
    personal_year_reading = Column(Text)
    personal_year_cycle_stage = Column(Integer)  # 1-9 in 9-year cycle
    
    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow)
    last_updated = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    user = relationship("User")


class WinProbabilityModel(Base):
    """Predict user's winning probability based on multiple factors"""
    __tablename__ = "win_probability_models"
    
    id = Column(Integer, primary_key=True)
    user_id = Column(Integer, ForeignKey('users.id'))
    
    # Model inputs
    lottery_type = Column(String(50))
    
    # Probability scores (0-100)
    base_probability = Column(Float)  # Mathematical probability
    numerology_boost = Column(Float)  # Numerology-based adjustment
    astrological_influence = Column(Float)  # Current planetary positions
    historical_performance = Column(Float)  # User's past performance
    lucky_day_bonus = Column(Float)  # Today is lucky day?
    lucky_hour_bonus = Column(Float)  # Current hour is lucky?
    
    # Final prediction
    predicted_win_probability = Column(Float)  # Weighted combination
    confidence_score = Column(Float)  # 0-1, how confident is model?
    
    # Recommendations
    recommended_numbers = Column(JSON)  # [List of recommended numbers]
    avoid_numbers = Column(JSON)  # [List of numbers to avoid]
    best_time_to_play = Column(String(50))  # "morning", "afternoon", "evening", "night"
    best_days_to_play = Column(JSON)  # [List of day names]
    
    # Winning indicators
    hot_numbers_influence = Column(Float)  # How many hot numbers in prediction?
    cold_numbers_influence = Column(Float)  # How many cold numbers?
    numerology_match = Column(Float)  # How well do numbers match numerology?
    
    # User feedback
    actual_result = Column(String(20))  # "win", "loss", "pending"
    user_won = Column(Boolean)
    
    # Timestamps
    predicted_at = Column(DateTime, default=datetime.utcnow)
    lottery_date = Column(DateTime)  # When this lottery draws
    result_at = Column(DateTime)  # When result was recorded
    
    user = relationship("User")


class LotteryStatistics(Base):
    """Track statistical patterns for each user"""
    __tablename__ = "lottery_statistics"
    
    id = Column(Integer, primary_key=True)
    user_id = Column(Integer, ForeignKey('users.id'), unique=True)
    lottery_type = Column(String(50))
    
    # Hot & Cold numbers
    hot_numbers = Column(JSON)  # Numbers that appeared frequently
    cold_numbers = Column(JSON)  # Numbers that appeared rarely
    hot_count = Column(JSON)  # How many times each hot number appeared
    cold_count = Column(JSON)  # How many times each cold number appeared
    
    # Frequency analysis
    most_played_numbers = Column(JSON)  # Numbers user played most
    most_winning_numbers = Column(JSON)  # Numbers that won for user
    least_winning_numbers = Column(JSON)  # Numbers that lost
    
    # Patterns
    number_sequences = Column(JSON)  # Consecutive numbers in plays
    gap_analysis = Column(JSON)  # Gaps between numbers
    even_odd_ratio = Column(Float)  # Ratio of even to odd numbers
    prime_number_ratio = Column(Float)  # How many primes?
    
    # Trends
    numbers_due_to_appear = Column(JSON)  # Haven't appeared in while
    numbers_appearing_too_often = Column(JSON)  # Appeared too many times
    trend_direction = Column(String(20))  # "increasing", "decreasing", "stable"
    
    # Personal stats
    total_plays = Column(Integer, default=0)
    total_wins = Column(Integer, default=0)
    win_rate = Column(Float, default=0.0)  # Percentage
    average_spend = Column(Float, default=0.0)
    average_winnings = Column(Float, default=0.0)
    roi = Column(Float, default=0.0)  # Return on investment
    
    # Streaks
    current_winning_streak = Column(Integer, default=0)
    current_losing_streak = Column(Integer, default=0)
    longest_winning_streak = Column(Integer, default=0)
    longest_losing_streak = Column(Integer, default=0)
    
    # Time analysis
    most_active_day = Column(String(20))  # Day of week
    most_active_hour = Column(Integer)  # Hour of day
    last_play_date = Column(DateTime)
    days_since_last_play = Column(Integer)
    
    # Updated
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    user = relationship("User")


class DailyAIInsight(Base):
    """Enhanced daily insights with AI recommendations"""
    __tablename__ = "daily_ai_insights"
    
    id = Column(Integer, primary_key=True)
    user_id = Column(Integer, ForeignKey('users.id'))
    date = Column(DateTime, default=datetime.utcnow)
    
    # Core insight
    title = Column(String(200))
    description = Column(Text)
    
    # Horoscope
    horoscope = Column(Text)  # Daily horoscope reading
    mood = Column(String(50))  # Happy, Neutral, Cautious
    energy_level = Column(Integer)  # 1-10
    
    # Lottery recommendations
    lottery_recommendation = Column(String(50))  # "play", "wait", "be_cautious"
    recommended_numbers = Column(JSON)  # [Recommended lucky numbers today]
    avoid_numbers = Column(JSON)  # [Numbers to avoid today]
    
    # Timing
    lucky_hours = Column(JSON)  # [Hours of highest probability]
    best_time_of_day = Column(String(50))  # "morning", "afternoon", "evening"
    
    # Planetary influence
    ruling_planet = Column(String(50))
    planetary_influence = Column(Text)  # How planets affect today
    mercury_retrograde = Column(Boolean)
    
    # Health & Wellness
    health_advice = Column(Text)  # General wellness advice
    meditation_recommendation = Column(Text)
    breathing_exercise = Column(Text)
    
    # Financial advice
    financial_advice = Column(Text)
    spending_forecast = Column(String(50))  # "cautious", "moderate", "favorable"
    
    # Relationship advice
    relationship_advice = Column(Text)
    love_forecast = Column(String(50))  # "positive", "neutral", "challenging"
    
    # Career advice
    career_advice = Column(Text)
    work_focus = Column(Text)  # What to focus on at work today
    
    # Lucky items
    lucky_color_of_day = Column(String(50))
    lucky_gemstone = Column(String(50))
    lucky_scent = Column(String(50))
    
    # Challenge/opportunity
    daily_challenge = Column(Text)  # Challenge to overcome today
    daily_opportunity = Column(Text)  # Opportunity to seize
    
    # Affirmation
    daily_affirmation = Column(Text)  # Positive affirmation for the day
    
    # User engagement
    liked = Column(Boolean, default=False)
    saved = Column(Boolean, default=False)
    shared = Column(Boolean, default=False)
    
    created_at = Column(DateTime, default=datetime.utcnow)
    
    user = relationship("User")


class AnalyticalDashboard(Base):
    """Consolidated analytics for user dashboard"""
    __tablename__ = "analytical_dashboards"
    
    id = Column(Integer, primary_key=True)
    user_id = Column(Integer, ForeignKey('users.id'), unique=True)
    
    # Summary statistics
    total_plays_all_time = Column(Integer, default=0)
    total_plays_month = Column(Integer, default=0)
    total_plays_week = Column(Integer, default=0)
    
    total_winnings = Column(Float, default=0.0)
    total_spent = Column(Float, default=0.0)
    net_profit_loss = Column(Float, default=0.0)
    overall_roi = Column(Float, default=0.0)
    
    # Rankings
    user_rank_all_time = Column(Integer)  # By wins
    user_rank_month = Column(Integer)
    user_rank_week = Column(Integer)
    percentile_rank = Column(Float)  # Top X%
    
    # Insights
    biggest_win = Column(Float)
    biggest_loss = Column(Float)
    most_frequent_number = Column(Integer)
    most_winning_number = Column(Integer)
    
    # Predictions
    next_predicted_lucky_number = Column(Integer)
    next_predicted_lucky_date = Column(DateTime)
    predicted_monthly_winnings = Column(Float)
    
    # Behavioral
    play_frequency = Column(String(50))  # "daily", "weekly", "monthly", "occasional"
    favorite_lottery_type = Column(String(50))
    best_performing_lottery = Column(String(50))
    
    # Numerology
    personal_lucky_number = Column(Integer)
    numerology_compatibility_score = Column(Float)  # 0-100
    
    # Recommendations
    primary_recommendation = Column(String(200))  # Main recommendation
    secondary_recommendations = Column(JSON)  # List of other recommendations
    
    # Last updated
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    user = relationship("User")
