# A generic, database agnostic set of migrations,
# that can be used alongside the existing Flask-Alembic extension.

from alembic import context
from logging.config import fileConfig
import logging

# this is the Alembic Config object, which provides
# the values of various Alembic directives.
config = context.config

# Interpret the config file for Python logging.
# This line sets up loggers basically.
if config.config_file_name is not None:
    fileConfig(config.config_file_name)
logger = logging.getLogger('alembic.env')
